<!DOCTYPE html>
<html>
<head>
	<title>Php Dice Game</title>
</head>
<body>
	<h1>PHP Dice Game</h1>
	<p>This game allow a user to enter a number after entering a number then the game generate a random number(1-6) if the number entered by the the user match the number generated by the game the user win! the game.</p><br><br>
	<form action="dice.php" method="POST">
		Enter Dice number:<input type="number" name="dice_number">
		<input type="submit" name="submit" value="roll Dice">
		
	</form><br>

	<?php

   if(isset($_POST['submit']))
   {

   	$dice_number = $_POST['dice_number']; 
	   	if(!empty($dice_number)) // checking if number entered is not empty
	   	{
            $game_number_generated = rand(1,6); // generating a random number between 1 to 6
            echo "you entered this number $dice_number<br>";
            echo "The game generated this number $game_number_generated<br>";

            if(	$dice_number  ==  $game_number_generated) // checking if number entered is equal to number generated 
            {
            	echo "<b>well done you have win the game</b><br>";
            }
            else
            {
            	echo "Sorry you did not win the game try again";
            }
	   	}
	   	else
	   	{
	   		echo "<p><b>Please Enter Dice number</b></p>"; // displaying this message if a number is not entered
	   	}
   }


	?>

</body>
</html>